apiVersion: v1
kind: Service
metadata:
  name: cast-service
spec:
  selector:
    app: cast-service
  ports:
    - protocol: TCP
      port: {{ .Values.castService.service.port }}
      targetPort: 8000
  type: {{ .Values.castService.service.type }}