apiVersion: v1
kind: Secret
metadata:
  name: cast-db-secret
type: Opaque
stringData:
  POSTGRES_USER: "{{ .Values.castDb.auth.username }}"
  POSTGRES_PASSWORD: "{{ .Values.castDb.auth.password }}"
  POSTGRES_DB: "{{ .Values.castDb.auth.database }}"