apiVersion: v1
kind: Service
metadata:
  name: cast-db
spec:
  selector:
    app: cast-db
  ports:
    - protocol: TCP
      port: {{ .Values.castDb.service.port }}
      targetPort: 5432
  type: ClusterIP