apiVersion: v1
kind: Secret
metadata:
  name: movie-db-secret
type: Opaque
stringData:
  POSTGRES_USER: "{{ .Values.movieDb.auth.username }}"
  POSTGRES_PASSWORD: "{{ .Values.movieDb.auth.password }}"
  POSTGRES_DB: "{{ .Values.movieDb.auth.database }}"