apiVersion: v1
kind: Service
metadata:
  name: movie-db
spec:
  selector:
    app: movie-db
  ports:
    - protocol: TCP
      port: {{ .Values.movieDb.service.port }}
      targetPort: 5432
  type: ClusterIP