movieService:
  replicaCount: 1
  image:
    repository: roxanaiuliamiu/movie-service
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 8000
  env:
    DATABASE_URI: "postgresql://movie_db_username:movie_db_password@movie-db/movie_db_dev"
    CAST_SERVICE_HOST_URL: "http://cast-service:8000/api/v1/casts/"

castService:
  replicaCount: 1
  image:
    repository: roxanaiuliamiu/cast-service
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 8000
  env:
    DATABASE_URI: "postgresql://cast_db_username:cast_db_password@cast-db/cast_db_dev"

movieDb:
  image:
    repository: postgres
    tag: "12.1-alpine"
    pullPolicy: IfNotPresent
  service:
    port: 5432
  auth:
    username: movie_db_username
    password: movie_db_password
    database: movie_db_dev

castDb:
  image:
    repository: postgres
    tag: "12.1-alpine"
    pullPolicy: IfNotPresent
  service:
    port: 5432
  auth:
    username: cast_db_username
    password: cast_db_password
    database: cast_db_dev

ingress:
  enabled: false
  className: nginx
  host: fastapi.local